spring:
  mvc:
   pathmatch:
     matching-strategy: ANT_PATH_MATCHER
   throw-exception-if-no-handler-found: true
  application:
    name: productprices-app
  datasource:
    url: jdbc:mariadb://mariadb-docker:3306/products
    username: root
    password: R3do-docente
    driver-class-name: org.mariadb.jdbc.Driver		
  #datasource:
    #driver-class-name: org.h2.Driver
    #username: user
    #password: pass
    #url: "jdbc:h2:mem:products;DB_CLOSE_ON_EXIT=FALSE"
  #h2:
    #console:
      #enabled: true
      #path: /h2-console
  jpa:
    show-sql: true
    # Cambiamos a 'update' para no perder tus datos en cada reinicio
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    # Mantenemos esto para dar tiempo a la DB a despertar
    defer-datasource-initialization: true
server:
  port: ${PORT:8080}   

java:
  version: 17     
